title: "Zettel"
baseURL: "https://bpampel.de/zettel"
languageCode: "en-us"
theme: "pulp"
canonifyURLs: true
sectionPagesMenu: "main"
enableRobotsTXT: true
enableGitInfo: true

params:
  Author: "Benjamin Trummer"
  publicationYear: 2025
  avatar: "baerli.jpg"
  avatarDescription: "cake eater"
  favicon: "note_box.ico"
  css: ["css/custom.css"]
  math: true
  dateFormat: "2006-01-01 17:00"


markup:
  highlight:
    style: monokai
    lineNos: true

outputs:
  section: ["JSON", "HTML"]
  term: ["JSON", "HTML"]
