title: "Zettel"
baseURL: "https://bpampel.de/zettel"
languageCode: "en-us"
theme: "pulp"
canonifyURLs: true
uglyurls: true
sectionPagesMenu: "main"
enableRobotsTXT: true

params:
  Author: "Benjamin Pampel"
  publicationYear: 2024
  avatar: "baerli.jpg"
  avatarDescription: "cake eater"
  favicon: "note_box.ico"
  css: ["css/custom.css"]
  math: true

markup:
  highlight:
    style: monokai
    lineNos: true

outputs:
  section: ["JSON", "HTML"]
  term: ["JSON", "HTML"]

